### ISSUE TITLE
Add title, e.g. "Endnotes" or just "Notes" before Footnotes?

### ISSUE THREAD

**Issue by ReaderGuy42** [alx-plugins/better-fn#15]
Is there a way to add a title such as Endnotes before the Footnotes at the bottom of the document?
Thanks :)

**Comment by aidenlx** [comment]
I think you can achieve this by css snippet: 

```css
section.footnotes:before {
    content: "EndNotes";
    font-size: 1em;
    font-weight: bold;
    margin-top: 26px;
}
section.footnotes > hr {
    margin-top: 0;
}

**Comment by ReaderGuy42** [comment]
Great, thanks, but now there's a huge gap/margin between the "End Notes" title and the line that goes before the actual footnotes.
Thanks!

**Comment by aidenlx** [comment]
You can try adjusting margin-top and margin-buttom of `hr` and `.footnote:before` based on your need

**Comment by ReaderGuy42** [comment]
Ok, I tried that. i have this as the snippet now

`section.footnotes:before {
    content: "End Notes";
    font-size: 2em;
    font-weight: bold;
    margin-top: 0px;
    margin-bottom: 0px;
}
section.footnotes > hr {
    margin-top: 0px;
    margin-bottom: 0px;
}`

But nothing changed.
