### ISSUE TITLE
Live Preview support

### ISSUE THREAD

**Issue by DutchPete** [alx-plugins/better-fn#17]
The plug-in worked up till Obsidian version 0.13.13 included. I just upgraded to 0.13.14 and it does not work anymore: I still get the little hand when I hover over the footnote, but I get no pop-up anymore.

I suspect due to Live Preview.

Do you plan to add support for LP?

**Comment by aidenlx** [comment]
I’ll investigate, the problem shouldn’t be LP since it only works in preview mode and doesn’t patch editor or rely on editor to work (and the plugin won’t support LP before editor improves footnote parsing)

**Comment by DutchPete** [comment]
OK, thanks in advance. I was surprised it stopped working with 0.13.14 since it was fine after the introduction of LP. Anyway, hopefully you can trace it.

**Comment by DutchPete** [comment]
Don't bother spending time on this, it is the theme I was using.
My apologies for this false alarm.
