### ISSUE TITLE
Feature: Footnote popover in source mode/Live preview

### ISSUE THREAD

**Issue by aidenlx** [alx-plugins/better-fn#2]

**Comment by NomarCub** [comment]
Now there's also Live Preview mode, where footnote popups would also be fitting.

**Comment by MILKMILKKING** [comment]
这是一款非常棒的插件，如果也能在Live Preview mode实现跳出预览就更好了!
This is a great plugin, and it would be great if you could also implement a pop-up preview in Live Preview mode!

**Comment by ycbrd** [comment]
Please, we could really use it.

**Comment by MiquelJorquera** [comment]
Bump! That would be amazing
