### ISSUE TITLE
[Feature Request] better use in preview mode

### ISSUE THREAD

**Issue by SYQsb** [alx-plugins/better-fn#36]
currently the plugin works perfectly, but in preview mode it has no popup preview. I suggest a temporary solution: add an option to put the footnote right under the current paragraph instead of the whole passage. This might be easier to achieve (I think?) before the compatibility to preview mode.

**Comment by trungtin** [comment]
I thought the plugin didn't work, but then read your comment and realized it will only show the popover in reading mode

**Comment by SYQsb** [comment]
> I thought the plugin didn't work, but then read your comment and realized it will only show the popover in reading mode

Yeah, but my daily mode is like 99% of preview mode. Reading mode is not so useful

**Comment by huachuman** [comment]
I was asking copilot how to modify it and it came back with this:

To make this work in live edit mode, you'll need to modify the modifyOnUnloadFile function in src/bf-main.ts to handle live edit mode.

Currently, it seems like the function is only handling the preview mode. You can check the mode of the current leaf using leaf.view.getViewState().mode. If the mode is 'source', then it's in live edit mode.

Here's a rough idea of how you might modify the function:
```
modifyOnUnloadFile: leafAction = (leaf) => {
  if (!isIntact(leaf.view)) return;
  const view = leaf.view;
  const mode = view.getViewState().mode;
  if (mode === 'source') {
    // Handle live edit mode
    // You might need to create a new function similar to onUnloadFile for live edit mode
  } else {
    // Existing code to handle preview mode
    const revert = around(leaf.view, {
      // eslint-disable-next-line prefer-arrow/prefer-arrow-functions
      onUnloadFile(next) {
        return function (this: any, ...args) {
          const bridgeEl = view.previewMode.containerEl.querySelector(
            ".markdown-preview-section",
          ) as BridgeEl;
          const { infoList, singleton } = bridgeEl;
          if (infoList) {
            infoList.forEach((info) => info.popover?.tippy.destroy());
            infoList.clear();
          }
          if (singleton) {
            singleton.destroy();
            bridgeEl.singleton = null;
          }
        };
      },
    });
  }
};

```
I'm not sure how to go about implementing that bu maybe this will give someone a hint

**Comment by huachuman** [comment]
It says this is completed but I'm not able to make it show a preview on hover no matter what I try
