### ISSUE TITLE
Popover not working with multiple label to the same reference

### ISSUE THREAD

**Issue by Masktial** [alx-plugins/better-fn#6]
![image](https://user-images.githubusercontent.com/82996431/120142245-903b4200-c210-11eb-9ea1-4e7b6d452693.png)

**[1]works
but[1-1] not working**

XDM~

**Comment by aidenlx** [comment]
原文markdown附上来吧，我测试一下

**Comment by Masktial** [comment]
来啦~：
```
这是一个可爱的测试[^AI];感谢大佬开发的插件^_^！[^AI]

[^AI]:yyds
```

**Comment by aidenlx** [comment]
等0.12.4正式发布就会发布修复了的新版本:)

**Comment by Masktial** [comment]
好~大佬翻译的真好(@ - @)b
